// Code generated by ogen, DO NOT EDIT.

package api

// Ref: #/components/schemas/CreateUploadResponse
type CreateUploadResponse struct {
	// Server-generated upload identifier.
	UploadId string `json:"uploadId"`
	// Pre-signed R2 PUT URL (expires in 1 hour).
	UploadUrl string `json:"uploadUrl"`
}

// GetUploadId returns the value of UploadId.
func (s *CreateUploadResponse) GetUploadId() string {
	return s.UploadId
}

// GetUploadUrl returns the value of UploadUrl.
func (s *CreateUploadResponse) GetUploadUrl() string {
	return s.UploadUrl
}

// SetUploadId sets the value of UploadId.
func (s *CreateUploadResponse) SetUploadId(val string) {
	s.UploadId = val
}

// SetUploadUrl sets the value of UploadUrl.
func (s *CreateUploadResponse) SetUploadUrl(val string) {
	s.UploadUrl = val
}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Errors  []ErrorResponseErrorsItem `json:"errors"`
	Success bool                      `json:"success"`
}

// GetErrors returns the value of Errors.
func (s *ErrorResponse) GetErrors() []ErrorResponseErrorsItem {
	return s.Errors
}

// GetSuccess returns the value of Success.
func (s *ErrorResponse) GetSuccess() bool {
	return s.Success
}

// SetErrors sets the value of Errors.
func (s *ErrorResponse) SetErrors(val []ErrorResponseErrorsItem) {
	s.Errors = val
}

// SetSuccess sets the value of Success.
func (s *ErrorResponse) SetSuccess(val bool) {
	s.Success = val
}

type ErrorResponseErrorsItem struct {
	Code    float64 `json:"code"`
	Message string  `json:"message"`
}

// GetCode returns the value of Code.
func (s *ErrorResponseErrorsItem) GetCode() float64 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ErrorResponseErrorsItem) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ErrorResponseErrorsItem) SetCode(val float64) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ErrorResponseErrorsItem) SetMessage(val string) {
	s.Message = val
}

// Ref: #/components/schemas/FinalizeUploadFailureResponse
type FinalizeUploadFailureResponse struct {
	BundleId     OptString                            `json:"bundleId"`
	Message      string                               `json:"message"`
	Success      FinalizeUploadFailureResponseSuccess `json:"success"`
	VersionLabel OptString                            `json:"versionLabel"`
	VersionName  OptString                            `json:"versionName"`
}

// GetBundleId returns the value of BundleId.
func (s *FinalizeUploadFailureResponse) GetBundleId() OptString {
	return s.BundleId
}

// GetMessage returns the value of Message.
func (s *FinalizeUploadFailureResponse) GetMessage() string {
	return s.Message
}

// GetSuccess returns the value of Success.
func (s *FinalizeUploadFailureResponse) GetSuccess() FinalizeUploadFailureResponseSuccess {
	return s.Success
}

// GetVersionLabel returns the value of VersionLabel.
func (s *FinalizeUploadFailureResponse) GetVersionLabel() OptString {
	return s.VersionLabel
}

// GetVersionName returns the value of VersionName.
func (s *FinalizeUploadFailureResponse) GetVersionName() OptString {
	return s.VersionName
}

// SetBundleId sets the value of BundleId.
func (s *FinalizeUploadFailureResponse) SetBundleId(val OptString) {
	s.BundleId = val
}

// SetMessage sets the value of Message.
func (s *FinalizeUploadFailureResponse) SetMessage(val string) {
	s.Message = val
}

// SetSuccess sets the value of Success.
func (s *FinalizeUploadFailureResponse) SetSuccess(val FinalizeUploadFailureResponseSuccess) {
	s.Success = val
}

// SetVersionLabel sets the value of VersionLabel.
func (s *FinalizeUploadFailureResponse) SetVersionLabel(val OptString) {
	s.VersionLabel = val
}

// SetVersionName sets the value of VersionName.
func (s *FinalizeUploadFailureResponse) SetVersionName(val OptString) {
	s.VersionName = val
}

func (*FinalizeUploadFailureResponse) postFinalizeUploadRes() {}

type FinalizeUploadFailureResponseSuccess bool

const (
	FinalizeUploadFailureResponseSuccessFalse FinalizeUploadFailureResponseSuccess = false
)

// AllValues returns all FinalizeUploadFailureResponseSuccess values.
func (FinalizeUploadFailureResponseSuccess) AllValues() []FinalizeUploadFailureResponseSuccess {
	return []FinalizeUploadFailureResponseSuccess{
		FinalizeUploadFailureResponseSuccessFalse,
	}
}

// Ref: #/components/schemas/FinalizeUploadSuccessResponse
type FinalizeUploadSuccessResponse struct {
	AppId        NilString                            `json:"appId"`
	BundleId     string                               `json:"bundleId"`
	Success      FinalizeUploadSuccessResponseSuccess `json:"success"`
	VersionLabel string                               `json:"versionLabel"`
	VersionName  string                               `json:"versionName"`
}

// GetAppId returns the value of AppId.
func (s *FinalizeUploadSuccessResponse) GetAppId() NilString {
	return s.AppId
}

// GetBundleId returns the value of BundleId.
func (s *FinalizeUploadSuccessResponse) GetBundleId() string {
	return s.BundleId
}

// GetSuccess returns the value of Success.
func (s *FinalizeUploadSuccessResponse) GetSuccess() FinalizeUploadSuccessResponseSuccess {
	return s.Success
}

// GetVersionLabel returns the value of VersionLabel.
func (s *FinalizeUploadSuccessResponse) GetVersionLabel() string {
	return s.VersionLabel
}

// GetVersionName returns the value of VersionName.
func (s *FinalizeUploadSuccessResponse) GetVersionName() string {
	return s.VersionName
}

// SetAppId sets the value of AppId.
func (s *FinalizeUploadSuccessResponse) SetAppId(val NilString) {
	s.AppId = val
}

// SetBundleId sets the value of BundleId.
func (s *FinalizeUploadSuccessResponse) SetBundleId(val string) {
	s.BundleId = val
}

// SetSuccess sets the value of Success.
func (s *FinalizeUploadSuccessResponse) SetSuccess(val FinalizeUploadSuccessResponseSuccess) {
	s.Success = val
}

// SetVersionLabel sets the value of VersionLabel.
func (s *FinalizeUploadSuccessResponse) SetVersionLabel(val string) {
	s.VersionLabel = val
}

// SetVersionName sets the value of VersionName.
func (s *FinalizeUploadSuccessResponse) SetVersionName(val string) {
	s.VersionName = val
}

func (*FinalizeUploadSuccessResponse) postFinalizeUploadRes() {}

type FinalizeUploadSuccessResponseSuccess bool

const (
	FinalizeUploadSuccessResponseSuccessTrue FinalizeUploadSuccessResponseSuccess = true
)

// AllValues returns all FinalizeUploadSuccessResponseSuccess values.
func (FinalizeUploadSuccessResponseSuccess) AllValues() []FinalizeUploadSuccessResponseSuccess {
	return []FinalizeUploadSuccessResponseSuccess{
		FinalizeUploadSuccessResponseSuccessTrue,
	}
}

// NewNilString returns new NilString with value set to v.
func NewNilString(v string) NilString {
	return NilString{
		Value: v,
	}
}

// NilString is nullable string.
type NilString struct {
	Value string
	Null  bool
}

// SetTo sets value to v.
func (o *NilString) SetTo(v string) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilString) SetToNull() {
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPostFinalizeUploadReq returns new OptPostFinalizeUploadReq with value set to v.
func NewOptPostFinalizeUploadReq(v PostFinalizeUploadReq) OptPostFinalizeUploadReq {
	return OptPostFinalizeUploadReq{
		Value: v,
		Set:   true,
	}
}

// OptPostFinalizeUploadReq is optional PostFinalizeUploadReq.
type OptPostFinalizeUploadReq struct {
	Value PostFinalizeUploadReq
	Set   bool
}

// IsSet returns true if OptPostFinalizeUploadReq was set.
func (o OptPostFinalizeUploadReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPostFinalizeUploadReq) Reset() {
	var v PostFinalizeUploadReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPostFinalizeUploadReq) SetTo(v PostFinalizeUploadReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPostFinalizeUploadReq) Get() (v PostFinalizeUploadReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPostFinalizeUploadReq) Or(d PostFinalizeUploadReq) PostFinalizeUploadReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type PostCreateUploadForbidden ErrorResponse

func (*PostCreateUploadForbidden) postCreateUploadRes() {}

type PostCreateUploadOK struct {
	Result  CreateUploadResponse `json:"result"`
	Success bool                 `json:"success"`
}

// GetResult returns the value of Result.
func (s *PostCreateUploadOK) GetResult() CreateUploadResponse {
	return s.Result
}

// GetSuccess returns the value of Success.
func (s *PostCreateUploadOK) GetSuccess() bool {
	return s.Success
}

// SetResult sets the value of Result.
func (s *PostCreateUploadOK) SetResult(val CreateUploadResponse) {
	s.Result = val
}

// SetSuccess sets the value of Success.
func (s *PostCreateUploadOK) SetSuccess(val bool) {
	s.Success = val
}

func (*PostCreateUploadOK) postCreateUploadRes() {}

type PostCreateUploadUnauthorized ErrorResponse

func (*PostCreateUploadUnauthorized) postCreateUploadRes() {}

type PostFinalizeUploadForbidden ErrorResponse

func (*PostFinalizeUploadForbidden) postFinalizeUploadRes() {}

type PostFinalizeUploadNotFound ErrorResponse

func (*PostFinalizeUploadNotFound) postFinalizeUploadRes() {}

type PostFinalizeUploadReq struct {
	// Upload ID returned by POST /api/v1/uploads.
	ID string `json:"id"`
}

// GetID returns the value of ID.
func (s *PostFinalizeUploadReq) GetID() string {
	return s.ID
}

// SetID sets the value of ID.
func (s *PostFinalizeUploadReq) SetID(val string) {
	s.ID = val
}

type PostFinalizeUploadUnauthorized ErrorResponse

func (*PostFinalizeUploadUnauthorized) postFinalizeUploadRes() {}
