// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/url"
	"strings"

	"github.com/go-faster/errors"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/uri"
)

func trimTrailingSlashes(u *url.URL) {
	u.Path = strings.TrimRight(u.Path, "/")
	u.RawPath = strings.TrimRight(u.RawPath, "/")
}

// Invoker invokes operations described by OpenAPI v3 specification.
type Invoker interface {
	// PostCreateUpload invokes post_CreateUpload operation.
	//
	// Create a simulator build upload.
	//
	// POST /api/v1/uploads
	PostCreateUpload(ctx context.Context) (PostCreateUploadRes, error)
	// PostFinalizeUpload invokes post_FinalizeUpload operation.
	//
	// Finalize a build upload.
	//
	// POST /api/v1/uploads/finalize
	PostFinalizeUpload(ctx context.Context, request OptPostFinalizeUploadReq) (PostFinalizeUploadRes, error)
}

// Client implements OAS client.
type Client struct {
	serverURL *url.URL
	baseClient
}

// NewClient initializes new Client defined by OAS.
func NewClient(serverURL string, opts ...ClientOption) (*Client, error) {
	u, err := url.Parse(serverURL)
	if err != nil {
		return nil, err
	}
	trimTrailingSlashes(u)

	c, err := newClientConfig(opts...).baseClient()
	if err != nil {
		return nil, err
	}
	return &Client{
		serverURL:  u,
		baseClient: c,
	}, nil
}

type serverURLKey struct{}

// WithServerURL sets context key to override server URL.
func WithServerURL(ctx context.Context, u *url.URL) context.Context {
	return context.WithValue(ctx, serverURLKey{}, u)
}

func (c *Client) requestURL(ctx context.Context) *url.URL {
	u, ok := ctx.Value(serverURLKey{}).(*url.URL)
	if !ok {
		return c.serverURL
	}
	return u
}

// PostCreateUpload invokes post_CreateUpload operation.
//
// Create a simulator build upload.
//
// POST /api/v1/uploads
func (c *Client) PostCreateUpload(ctx context.Context) (PostCreateUploadRes, error) {
	res, err := c.sendPostCreateUpload(ctx)
	return res, err
}

func (c *Client) sendPostCreateUpload(ctx context.Context) (res PostCreateUploadRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/api/v1/uploads"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodePostCreateUploadResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// PostFinalizeUpload invokes post_FinalizeUpload operation.
//
// Finalize a build upload.
//
// POST /api/v1/uploads/finalize
func (c *Client) PostFinalizeUpload(ctx context.Context, request OptPostFinalizeUploadReq) (PostFinalizeUploadRes, error) {
	res, err := c.sendPostFinalizeUpload(ctx, request)
	return res, err
}

func (c *Client) sendPostFinalizeUpload(ctx context.Context, request OptPostFinalizeUploadReq) (res PostFinalizeUploadRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/api/v1/uploads/finalize"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodePostFinalizeUploadRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodePostFinalizeUploadResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}
