// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *PostFinalizeUploadReq) setDefaults() {
	{
		val := bool(false)
		s.AllowDuplicateVersion.SetTo(val)
	}
}
